# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28fb75c4a6f33b3f6c17a5143036050a912dd520dc8e634bf237918d751e2d935d0e5b45e9e0255dae290d8b10c1cbfb5e68470328e2dd1e76ec06b366d42424

test:
  secret_key_base: dbe1fee945f85c10e763223f0b407a9861bb48b0d751efede1b06f876c4d88b74665eb8a0d855f02018fdc2881d5750d49ec27a9c3849cb6bad5462b3473ce1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
